### ISSUE TITLE
Detect when OH1 is removed from skin

### ISSUE THREAD

**Issue by johndefalco** [polarofficial/polar-ble-sdk#131]
My app needs to detect when if the OH1 sensor is accidentally removed while monitoring heart rate.  I am getting erratic readings from the sensor.  Sometimes it will return HR = 0 within 10-40 seconds of being removed, other times, it will just return random heart rate readings.

What is the recommended logic for detecting if the OH1 loses contact with the user's heart rate?

**Comment by JOikarinen** [comment]
@johndefalco The `contactStatusSupported` bit in [PolarHrData](https://github.com/polarofficial/polar-ble-sdk/blob/7810974560d9d6c23d7b9f9863eb2563eaf73e01/sources/Android/android-communications/src/main/java/polar/com/sdk/api/model/PolarHrData.java#L36) is false for Polar OH1 and for Polar Verity Sense. That is because the detection of the skin contact is challenging to implement reliably. If the optical heart sensor is not contacting the skin it is likely that optical measurement unit gets light from the surrounding environment. That is why you see random values once the OH1 is removed.

As that being said I don't have good advices for you problem. Maybe a logic written to your app which detect sudden changes in heart rate values could be an option.
