### ISSUE TITLE
Polar mobile SDK and Vantage V

### ISSUE THREAD

**Issue by jesselindberg** [polarofficial/polar-ble-sdk#182]
Hi guys. Quick question on whether it's possible to extract real-time heart rate from the Vantage V using the SDK? I'm not 100% sure based on the docs, by testing the SDK I only seem to get data from my H10.

Best,
Jesse

**Comment by JOikarinen** [comment]
@jesselindberg at the moment it is not possible to get data from Vantaga V or from other Polar wrist units using the SDK. Only the sensors supported, i.e. H10, Verity Sense, OH1 and H9

**Comment by JOikarinen** [comment]
Hi @jesselindberg, 

thanks for the feature request. The SDK support for the watches will be considered in the future. By SDK support, I mean that watches could stream accelerometer, gyroscope and other data what is possible from Polar sensors already. 

What comes to the heart rate, here is the update since previous discussion: 

The [standard BLE heart rate service](https://www.bluetooth.com/specifications/specs/heart-rate-service-1-0/) can be turned on in the latest Polar watches. The instructions how the heart rate service is turned on in the Polar watch, you may check the instructions for [Polar Ignite 2](https://support.polar.com/e_manuals/ignite-2/polar-ignite-2-user-manual-english/hr-sensor-mode.htm). Polar BLE SDK has the BLE heart rate client build in, so you may use Polar BLE SDK to connect and receive the heart rate from Polar watch.

**Comment by jesselindberg** [comment]
Thanks for the quick reply!

The heart rate service looks nice, but I take it's not available or coming to the first Vantage?
