### ISSUE TITLE
iOS Demo App build Error no such module PolarBleSdk

### ISSUE THREAD

**Issue by vivankk** [polarofficial/polar-ble-sdk#275]
***Platform your question concerns:*** 
- [ ] Android 
- [x] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [x] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**
I cloned this repo and opened the demo app with XCode. I also used the "Add packages" to add this repo, after having the import error, but the import error remains.
How do I get the app running with XCode? I am new to App development.

My ultimate goal is to read out all the data that is already stored on the Polar H10 from wearing it all day.

**Comment by JOikarinen** [comment]
Hi @vivankk,

you tried with [iOS example app](https://github.com/polarofficial/polar-ble-sdk/tree/master/examples/example-ios/iosBleSdkTestApp), right?  Once you have cloned the repo, you may just open the iOS example project with Xcode. You shall open the [iosBleSdkTestApp.xcworkspace](https://github.com/polarofficial/polar-ble-sdk/tree/master/examples/example-ios/iosBleSdkTestApp/iosBleSdkTestApp.xcworkspace) and you are good to go. You can build and install the example project just like that. That is because example project takes the Polar BLE SDK as Cocoapods dependency and all the dependencies are pushed to version control.
