### ISSUE TITLE
Does requesting streaming feature on PolarBleApiDefaultImpl drain battery?

### ISSUE THREAD

**Issue by sammyfdm** [polarofficial/polar-ble-sdk#283]
***Platform your question concerns:*** 
- [ ] Android 
- [X] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [X] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**

I'm using the polar SDK for my iOS app and I want to turn on ECG streaming for users based on a feature flag (some users will have it but others won't). I'm curious to know if I instantiate the PolarBleApiDefaultImpl with `Features.polarSensorStreaming`, but _don't_ actually go through with subscribing to the ECG data stream, will the polar device still be draining the battery faster?

Here's the instantiation code:
```
api = PolarBleApiDefaultImpl.polarImplementation(DispatchQueue.main, features: Features.hr.rawValue | Features.batteryStatus.rawValue | Features.polarFileTransfer.rawValue | Features.polarSensorStreaming.rawValue)
```

And for users who are allowed to stream ECG, they would then go through the process of `api.requestStreamSettings(sensorId, feature: .ecg)` and then `api.startEcgStreaming(sensorId, settings: settings)`. Users who aren't allowed, would not have these calls made.

**Comment by JOikarinen** [comment]
Hi @sammyfdm, sorry for a bit delayed response. 

If you instantiate the the `api = PolarBleApiDefaultImpl.polarImplementation(DispatchQueue.main, features: Features.hr.rawValue | Features.batteryStatus.rawValue | Features.polarFileTransfer.rawValue | Features.polarSensorStreaming.rawValue)` no extra battery drain happen either on the phone or the H10 device. However, once BLE connection is created then small extra battery drain on H10 is caused by the BLE connection. Minor addtional battery drain will happen on H10 once you call the `api.startEcgStreaming(sensorId, settings: settings)`

To sum up:
- H10 turns itself on once worn on and finally turns it self off when not worn. This will be the **base battery drain**. 
- Battery drain on H10 will rise a bit when BLE connection is created between mobile and H10. 
- Battery drain on H10 will rise a bit more when `api.startEcgStreaming`
- at the moment I don't have exact numbers how much the battery drain will rise when BLE connected and ECG stream started. However, I would guess either of those is not significantly increasing the battery drain. It is the **base battery drain** which is the dominant battery consumer. The most effective way to save the battery is to follow the [wear instructions](https://support.polar.com/e_manuals/h10-heart-rate-sensor/polar-h10-user-manual-english/wear-the-heart-rate-sensor.htm) given for H10. [By the specification](https://support.polar.com/e_manuals/h10-heart-rate-sensor/polar-h10-user-manual-english/technical-specifications.htm) the H10 battery lasts around 400 hours of usage.
