### ISSUE TITLE
Is it possible to use multiple sensors?

### ISSUE THREAD

**Issue by martin-blaus** [polarofficial/polar-ble-sdk#289]
***Platform your question concerns:*** 
- [x] Android 
- [ ] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [ ] Polar H10
- [x] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**
Hi, I'm figuring out how to use polar h9's to collect and visualize data in our gym, unfortunately we dont own an ipad so we can't use team pro and since for now I just want to display HR I'm looking into a custom solution.
So the question is 2 fold: 
1. Is it possible with the sdk and an android device to connect multiple sensors (I currently own only 1)
2. Is there any alternatives out there built for android already?

Thanks

**Comment by JOikarinen** [comment]
Hi @martin-blaus,

> 1. Is it possible with the sdk and an android device to connect multiple sensors (I currently own only 1)
- yes it is. The limiting factor for amount of parallel BLE connections is not the SDK, but the capabilities on phone (or tablet). Yes, the different phone manufacturers has really big variation how the BLE is working (i.e. different hardware and software used).  I haven't tested lately the maximum amount of parallel BLE connections on any phone, but I believe almost any phone can keep at least five parallel connections. The problem with the parallel connections is the variation between the phones, let's say you tested your solution workable on one phone (or table). The working phone can hold reliably 10 parallel connections, but then you will install the application to another phone and you notice your solution is broken because on that phone just because it can't handle all the connections. 

- alternative solution is that you don't create the BLE connections, but listen the broadcast (BLE advertisement) sent by H9 device(s). On this approach you may listen easily dozens of devices without phone capabilities limiting the functionality.   

- So as a sum up, depends on your solution whether you want to create the actual BLE connection with the H9 or listen the BLE broadcast from it. Both of the approaches are possible with the Polar BLE SDK.  

- comparison of mentioned approaches:
    - Heart rate with the BLE Connection:
        - Heart rate specification is standard BLE, so if you get your solution working with Polar H9, the solution will work with any manufacturer following the BLE HR standard. That is basically all the heart rate sensors on the market. 
   - BLE broadcast:
        - Polar proprietary, so if you get your solution working with Polar H9, the solution will work Polar devices. Easily with the H9, H10 and VeritySense, but also with Polar wrist unit. With Polar wrist units this approach may need actions by the wrist unit user.

**Comment by martin-blaus** [comment]
First of all thanks a lot for the quick response.

I will try out the BLE brodcast capabilities, our idea is to work with polar given the quality of the meassuremnts and it seems like the simplest flow with the most capablities.
