### ISSUE TITLE
Continuously record and intermittent sync - Verity

### ISSUE THREAD

**Issue by wild-ig** [polarofficial/polar-ble-sdk#334]
***Platform your question concerns:*** 
- [X] Android 
- [X] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [X] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

Assume we wish to continuously record Accelerometer and Gyroscope @52Hz. No other data values are required.
Apologies, several noob questions follow:

At that data rate, on the Verity Sense, how long before the storage would be full?
From full charge, what is the expected battery operating time if the device is just recording and storing these data points (assume no lights are required and it is not streaming via BLE at the same time)?

If we wish to continuously record and at various intervals synchronize the data before the storage is full and assume we use a mobile App to sync the data from the device at intervals before full, can the SDK/device operate in that manner?
Does it need to be user initiated after power on?
Are there specific modes to methods to set or switch the device/SDK between recording and syncing?

Any other items to consider?

**Comment by andYgnite** [comment]
Hi @wild-ig 

If you would like to record ACC and GYRO @52Hz only you should be able to record at least 6 hours.

Please keep in mind that the recorded data are compressed, and the algorithm's performance depends on the level of movement. The more movement there is, the less the compression rate will be. Due to this variability, I recommend conducting a few tests with your specific application. This will provide a better estimation of both the recording time before the memory is full and the battery life.

To sync data, you need to stop the recording, read recorded files, delete recorded files to free up memory and restart the internal recording feature.
User init is not relevant for this feature.
