### ISSUE TITLE
How can we calculate frequency for PPG data using Polar device? For now i have set the sample rate to 135hz but its not giving me 135 records its giving me more than that after enabling sdk mode.

### ISSUE THREAD

**Issue by SohamSimform** [polarofficial/polar-ble-sdk#378]
***Platform your question concerns:*** 
- [o] Android 
- [ ] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [o] Polar OH1
- [o] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**

**Comment by jimmyzumthurm** [comment]
@SohamSimform Hi, PPG data that comes from Verity Sense contains 4 channels, there is 3 green channels and 1 for ambient light. This might be why you see more data than what you expect. 

Also note that there was a bug with older Verity Sense firmware versions about sampling rate : https://github.com/polarofficial/polar-ble-sdk/blob/master/documentation/KnownIssues.md This is fixed with latest 2.1.0 firmware
