### ISSUE TITLE
streaming HR is always zero when doing offline recording PPI

### ISSUE THREAD

**Issue by HiroyukiTamura** [polarofficial/polar-ble-sdk#411]
***Platform your question concerns:*** 
- [x] Android 
- [ ] iOS
- [ ] Other
- [ ] Platform is not relevant for this question

***Device:***
- [ ] Polar OH1
- [x] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this question

**Description:**

according to the [document](https://github.com/polarofficial/polar-ble-sdk/blob/ead9a4077ebc31e745192e0effeebacfd0ec2fa9/documentation/OfflineRecordingExplained.md#considerations), we can'n get same type data from both of offline recording and streaming at the same time.

but when I tried to get streaming HR and offline recording PPI, the number of HR is always 0.
is this expected behavior?

#### the way I tried
1. connect to Polar Verity Sense
2. start getting streaming HR. at this time, `PolarHrSample.hr` seems correct
3. start recording PPI. the `PolarPpiSample.ppi` seems correct, but the both of the `PolarHrSample.hr` and the `PolarPpiSample.hr` is 0.

**Comment by jimmyzumthurm** [comment]
Hi @HiroyukiTamura ,

There is no conflict between streaming or "online" HR and PPI offline recording together. What is not supported is having online + offline PPI at the same time. You can have online + offline HR though, its the only exception. 

Important considerations with PPI : 

When you enable PPI recording, algorithm will reset itself and go into PPI mode. It will take 25 seconds to have any ouput because it needs enough data to process. Also, in PPI mode the algorithm is very sensitive to movement. If movement is here, it will output the last valid HR value it was able to calculate, and HR is to be seen as a side feature of PPI recording, and it is updated each 5 seconds only (update interval of PPI algorithm). So if you start PPI recording and start moving right after that you will always receives HR = 0, as algorithm was never able to calculate HR. PPI recording should only be done with no movement at all.
