### ISSUE TITLE
connectToDevice() function not working when app in background 

### ISSUE THREAD

**Issue by outsbook** [polarofficial/polar-ble-sdk#82]
**Device: Polar NH10**
I am using `api.connectToDevice(DEVICE_ID); `to connect the device within android foreground service.
In my app here is functionality if somehow the polar device disconnected then we try to connect the device with `api.connectToDevice(DEVICE_ID);` function.

**In Android Marshmallow**
It's working fine for both foreground mode and background mode.

**In Android 10**
It's working fine when the app in foreground mode but when the app is in background mode it's not working.

For your information I use `api.backgroundEntered();` and `api.foregroundEntered();`

Could anyone please help me to solved this issue?

_Thanks for reading..._

**Comment by kcbaruri** [comment]
Did you use as below?
 @Override
    protected void onPause() {
        super.onPause();
        polarBleApi.backgroundEntered();
    }

    @Override
    protected void onResume() {
        super.onResume();
        polarBleApi.foregroundEntered();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        polarBleApi.shutDown();
    }

**Comment by outsbook** [comment]
@kcbaruri Yes, I use all 3 functions as same as your example

**Comment by outsbook** [comment]
Finally I found the solution, it was location permission issue.
Need Background Location permission
`<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />`

**Comment by sach16795** [comment]
@JavaDeveloper08 Were you able to use the service to record values? Right now I can store the values in the main activity. But it will not do the same if the app is killed. I think a background service is needed. But my efforts to implement a service is failing due to some issue in requestStreamSettings method. 

If you have solved this issue please let me know if you can help me out. Thanks in advance.
